---
title: "Homework 1"
author: Sushupta Vijapur
output: github_document
---
This is my solution to HW1.

``` {r}
library(tidyverse)
```

## Problem 1

Create a data frame with the specified elements

``` {r}
prob1_df = 
tibble(
  samp = rnorm(10),
  samp_gt_0 = samp > 0,
char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
)
```

Take the mean of each variable in my data frame.
```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df,factor_vec))
```

I can take the mean of numbers and logical but not characters or factors.
* for "samp_gt_0, R is converting them to 0 and 1 before taking the mean

```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df,factor_vec))
```

The "as.numeric" function makes it clear that R converts logicals to 0 and 1.


## Problem 2